language: python
sudo: false

matrix:
  include:
    - env: ENV_FILE="ci/travis/36-latest-conda-forge.yaml"
    - env: ENV_FILE="ci/travis/37-latest-conda-forge.yaml"

install:
  # Install conda
  - |
    wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    bash miniconda.sh -b -p $HOME/miniconda
    export PATH="$HOME/miniconda/bin:$PATH"
    conda config --set always_yes yes --set changeps1 no --set show_channel_urls true
    conda update --quiet conda
    conda config --add channels conda-forge --force
    conda config --set channel_priority strict
    conda config --set safety_checks disabled

  # Install dependencies
  - conda env create --file="${ENV_FILE}"
  - source activate test
  - conda list
  - conda info --all

script:
  - python setup.py sdist >/dev/null
  - echo "check_stable=False" >libpysal/config.py
  - python setup.py install
  - python -c 'import libpysal; libpysal.examples.fetch_all()'
  - rm -rf /home/travis/pysal_data/StLouis
  - nosetests --with-doctest --verbose --with-coverage --cover-package=libpysal -I shapely_ext.py;
  #- cd doc; make pickle; make doctest

notifications:
    email:
        recipients:
            - sjsrey@gmail.com
            - levi.john.wolf@gmail.com
        on_success: change 
        on_failure: always

after_success:
  - coveralls
